#!/bin/sh

# Run the program in background if it exists
function background_run
{
    which $1 >/dev/null && $* &
}

# Run the program if it exists
function run
{
    which $1 >/dev/null && $*
}

function debug
{
    echo $* >> /t/xinitrc_debug
}

# -----------------------------------------------

# Setup mouse options (see `man 4 libinput)
#> Enable tap to click
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
#> Enable 2 finger tap for middle click
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Button Mapping Enabled' 0 1

# Setup keyboard mapping
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
setxkbmap -config ~/.config/xkbmap.config

# Setup X resources
[ -f ~/.Xresources ] && xrdb ~/.Xresources

# no beep
xset -b

# Load all ssh keys
eval `ssh-agent`
ssh-add `find ~/.ssh -name "id_*" -a \! -name "*.pub"`

# Warmer screen temperature at night
background_run redshift-gtk

# Run the compositor
[ -f ~/.config/compton ] && run compton --config ~/.config/compton -b
