" Generated by vim-plug
" Tue 23 Aug 2022 09:14:39 AM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['alpha-nvim'].commit = 'd688f46090a582be8f9d7b70b4cf999b780e993d'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-emoji'].commit = '19075c36d5820253d32e2478b6aaf3734aeaafa0'
silent! let g:plugs['cmp-path'].commit = '447c87cdd6e6d6a1d2488b1d43108bfa217f56e1'
silent! let g:plugs['cmp-tmux'].commit = 'e32f2f1417c9ff307ad348a134788eabd76c6112'
silent! let g:plugs['diffconflicts'].commit = '05e8d2e935a235b8f8e6d308a46a5f028ea5bf97'
silent! let g:plugs['fzf-lua'].commit = 'c56c492218ea94549b195fd3c48b760443bf0090'
silent! let g:plugs['git-messenger.vim'].commit = '6c0b55fb38d0e0633127823aab89b0676d13e509'
silent! let g:plugs['gitsigns.nvim'].commit = '1e107c91c0c5e3ae72c37df8ffdd50f87fb3ebfa'
silent! let g:plugs['gv.vim'].commit = '1507838ee67f9b298def89cbfc404a0fee4a4b8c'
silent! let g:plugs['heirline.nvim'].commit = '25fdf89320e0bf1beb0ab51c483f96fb3854af44'
silent! let g:plugs['indent-blankline.nvim'].commit = 'c15bbe9f23d88b5c0b4ca45a446e01a0a3913707'
silent! let g:plugs['nvim-cmp'].commit = '058100d81316239f3874064064f0f0c5d43c2103'
silent! let g:plugs['nvim-fzf'].commit = 'a8dc4bae4c1e1552e0233df796e512ab9ca65e44'
silent! let g:plugs['nvim-tree.lua'].commit = '259efeee62c7fb51abf299c2570cacbf4806e98a'
silent! let g:plugs['nvim-web-devicons'].commit = '2d02a56189e2bde11edd4712fea16f08a6656944'
silent! let g:plugs['plenary.nvim'].commit = '31807eef4ed574854b8a53ae40ea3292033a78ea'
silent! let g:plugs['vim-fugitive'].commit = 'b411b753f805b969cca856e2ae51fdbab49880df'
silent! let g:plugs['vim-plug'].commit = 'd94d234548a8fd6fa686812848f377f1419dafa1'
silent! let g:plugs['which-key.nvim'].commit = 'bd4411a2ed4dd8bb69c125e339d837028a6eea71'
silent! let g:plugs['xterm-color-table.vim'].commit = 'efa63b4311f6d1328d214bd93149c14c77c9dd7b'

PlugUpdate!

