#!/bin/bash

set -euo pipefail

if [[ $# == 0 ]]; then
  echo "Usage: $0 <requirement_file> [--force]"
  exit 1
fi
REQUIREMENT_FILEPATH="$1"

RECREATE_EXISTING=
if [[ $# == 2 ]] && [[ "$2" == "--force" ]]; then
  RECREATE_EXISTING=yes
fi

NVIM_VENV_DIR=${XDG_DATA_HOME:-~/.local/share}/nvim/py-venv

if [[ -d "$NVIM_VENV_DIR" ]]; then
  if [[ -n "$RECREATE_EXISTING" ]]; then
    echo "!! Nvim venv dir '$NVIM_VENV_DIR' already exists,"
    echo "!! and --force was passed"
    echo ">> Deleting it to recreate it."
    rm -rf "$NVIM_VENV_DIR"
  else
    echo "!! Nvim venv dir '$NVIM_VENV_DIR' already exists,"
    echo "!! use --force to re-create it."
    exit 1
  fi
  echo
fi

echo
echo ">> Creating venv '$NVIM_VENV_DIR'"
mkdir -vp "$NVIM_VENV_DIR"
python3 -m venv -- "$NVIM_VENV_DIR"

echo
echo ">> Activating venv.."
source "$NVIM_VENV_DIR/bin/activate"

echo
echo ">> Installing requirements from '$REQUIREMENT_FILEPATH'"
pip install -r "$REQUIREMENT_FILEPATH"

echo
echo ">> Done installing, pip freeze:"
pip freeze

echo
echo ">> Nvim python venv ready at '$NVIM_VENV_DIR'."
echo ">> Use 'let g:python3_host_prog = \"$NVIM_VENV_DIR/bin/python3\"' to use this venv"
