# Tmux config: General options
# vim: set ft=tmux:

# WARN: default cmd should to be configurable 👀
#   (or at least, skipped in the config)
# set -g default-command "env -u SHLVL $HOME/.nix-profile/bin/zsh"
set -g default-command "env -u SHLVL zsh" # 🤔

# Disable tmux's auto window renaming
set -g allow-rename off

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber all windows when one is killed
set -g renumber-windows on

# In tmux copy mode, mouse word selection uses these separators
set -g word-separators " \t\n{}[]()\"'`=,;:@"

# Set history size (default is ~2000)
set -g history-limit 30000

# Do not detach on session destroy, switch to another one
set -g detach-on-destroy off

# -----------------------------------------------------------
if -F "#{==:#{@mycfg-config-status},reloading}" {
  display-message "Config: General options reloaded!"
}
