# Options config
# vim: set ft=tmux:

# Setup host terminal knowledge to assume many features are supported.
# (Assuming Wezterm, which basically supports all-the-things \o/)
#
# Add common features
set -sa terminal-features "xterm-256color:256:RGB:hyperlinks"
# Add uncommon features:
# - usstyle: host term supports underline colors & styles
# - overline: host term supports line over text
# - sync: host term supports synchronized updates
set -sa terminal-features "xterm-256color:usstyle:overline:sixel:sync"
# (NOTE: -s: server option ; -a: append)
# DEBUG: Check effective terminal features with:
#   tmux display -p '#{client_termfeatures}'
# (note: might need to detach/re-attach to update terminal-features after config reload)

# Mouse setup
set -g mouse on

# Ensure the system clipbaord is never set by tmux when setting the tmux
# clipboard.
#
# => I want to completely separate tmux/system clipboard.
# When setting the system clipboard, I always bypass tmux anyway.
set -g set-clipboard off

# Set timeout escape for tmux, for proper nvim support
set -sg escape-time 10

# Set TERM for proper colors
set -g default-terminal "tmux-256color"

# Request focus events from the terminal if supported and pass them through to apps
set -g focus-events on

# -----------------------------------------------------------
if -F "#{==:#{@mycfg-config-status},reloading}" {
  display-message "Config: Terminal options reloaded!"
}
