# Tmux config: Plugin tmux-resurrect, to save/restore windows/panes layout
# vim: set ft=tmux:

# Keys used for save/restore.
set -g @resurrect-save    "S"
set -g @resurrect-restore "R"

# Setup lifecycle status flag
# Values: idle (default) | restoring | saving
# => Can be read from other parts of the config (e.g. to tmp disable auto-layout hooks).
set -g @mycfg-plugin-resurrect-status "idle"
set -g @resurrect-hook-pre-restore-all   "tmux set -g @mycfg-plugin-resurrect-status restoring"
set -g @resurrect-hook-post-restore-all  "tmux set -g @mycfg-plugin-resurrect-status idle"
# note: 'pre-save-all' hook doesn't exist by default, had to patch plugin sources (see Nix setup)
set -g @resurrect-hook-pre-save-all      "tmux set -g @mycfg-plugin-resurrect-status saving"
set -g @resurrect-hook-post-save-all     "tmux set -g @mycfg-plugin-resurrect-status idle"

# If the plugin file exists, source it. Otherwise display a short notice.
# Nix is expected to set TMUX_PLUGIN_RESURRECT_PATH to the plugin directory.
if-shell '[ -f "$TMUX_PLUGIN_RESURRECT_PATH/resurrect.tmux" ]' {
  run-shell "$TMUX_PLUGIN_RESURRECT_PATH/resurrect.tmux"
} {
  display-message "Plugin load failed: tmux-resurrect not found (set TMUX_PLUGIN_RESURRECT_PATH to enable)"
}

# -----------------------------------------------------------
if -F "#{==:#{@mycfg-config-status},reloading}" {
  display-message "Config: Plugin tmux-resurrect reloaded!"
}
