ORIGINAL_PATH=$PATH


# ------------------ setup other paths
OTHER_PATHS=()

# User bins
OTHER_PATHS+=(~/.bin)

# OSX bins
OTHER_PATHS+=(/usr/local/bin)

# Lua bins
OTHER_PATHS+=(~/.luarocks/bin)

# adb & fastboot PATH, installed using install.sh script at
# https://github.com/corbindavenport/nexus-tools
OTHER_PATHS+=(~/.nexustools)

# Python bins
OTHER_PATHS+=(~/.local/bin)

# NodeJS bins
OTHER_PATHS+=(~/node_modules/.bin)



# ------------------ load local per-machine config

[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local



# ------------------ set $PATH & env avrs

typeset -U path
path=(
  "${OTHER_PATHS[@]}" # Expand all other paths by elements
  $path
)

export GOPATH=$HOME/gocode

export PAGER="most"

# -+X (Disables the `-X` option) : Send alt-screen term init sequence if necessary
export LESS="-+X"

# man in vim!
export MANPAGER='nvim -R +Man!'

# `most` does not work with colors outputed by `bat` (the `cat` clone on steroids)
export BAT_PAGER="less"

export EDITOR="nvim"
export VISUAL="$EDITOR"

export GIT_EDITOR="$EDITOR"


# ------------------ fzf config

FZF_BEW_KEYBINDINGS_ARRAY=()

# input nav
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'alt-h:backward-char' --bind 'alt-l:forward-char')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'alt-b:backward-word' --bind 'alt-w:forward-word')

# suggestions nav
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'alt-j:down' --bind 'alt-k:up')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'tab:down' --bind 'shift-tab:up' --bind 'alt-g:jump')

# preview nav
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'alt-p:toggle-preview')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'pgup:preview-page-up' --bind 'pgdn:preview-page-down')

# selection
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'ctrl-j:accept')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'alt-a:toggle+down')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'alt-space:toggle+down')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'ctrl-a:select-all')
FZF_BEW_KEYBINDINGS_ARRAY+=(--bind 'change:top') # select best result on input change

FZF_BEW_LAYOUT_ARRAY=(--height=40% --reverse --inline-info)
# NOTE: --border is made of unicode symbols, and can break the display
#  (--> removed for now)

# highlight the current line
FZF_BEW_LAYOUT_ARRAY+=(--color='bg+:232,gutter:-1')

export FZF_BEW_KEYBINDINGS="${(j: :)FZF_BEW_KEYBINDINGS_ARRAY}"
export FZF_BEW_LAYOUT="${(j: :)FZF_BEW_LAYOUT_ARRAY}"
alias fzf-bew="fzf $FZF_BEW_KEYBINDINGS $FZF_BEW_LAYOUT"
