#!/bin/bash

function chronometer
{
  local quit
  trap 'echo; quit=1' SIGINT # Prevent lost result on ^C

  local start_tstamp=`date +%s`

  while [[ -z $quit ]]; do
    echo -ne "$(date -u --date @$(( `date +%s` - $start_tstamp )) +%M:%S)\r"
    sleep .1
  done

  date -u --date @$(( `date +%s` - $start_tstamp )) +%M:%S
}
