#! perl

=head1 NAME

meta8-osc - TODO brief

=head1 SYNOPSIS

   urxvt -pe meta8-osc

=head1 DESCRIPTION

activate with    "meta8;on"
desactivate with "meta8;off"

=cut


sub on_osc_seq_perl {
	my ($self, $osc, $resp) = @_;

	return unless $osc =~ s/^meta8;([^;]+)//;

	$self->{blu} = $self->overlay_simple (30, 10, "We cannot change x_resource at runtime :(");

	if ($1 eq "on") {
		$self->resource ("meta8", "true");
	} elsif ($1 eq "off") {
		$self->resource ("meta8", "false");
	} elsif ($1 eq "toggle") {
		my $value = $self->resource ("meta8");
		my $new_value = ($value eq "true" ? "false" : "true");
		$self->resource ("meta8", $new_value );
	}

	my $text = "Meta new state: ";
	$text .= $self->resource ("meta8");

	$self->{overlay} = $self->overlay_simple (0, 0, $text);

	urxvt::timer ->new ->start (urxvt::NOW + 5) ->cb(sub {
			delete $self->{blu};
			delete $self->{overlay};
		});

	1
}

